name: ureport_ecaro
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.4+5

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  platform: ^3.1.0
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  # state management
  provider: ^6.0.5
  # nettwork handling
  dio: ^4.0.6
  http: ^0.13.5
  # singleton
  get_it: ^7.2.0
  # storage handling
  get_storage: ^2.0.3
  # keyboard handling
  flutter_keyboard_visibility: ^5.4.0
  #Sqflite
  sqflite:
  share: ^2.0.1
  intl: ^0.17.0
  flutter_localizations: # Add this line
    sdk: flutter

  # firebase config
  firebase_messaging: ^14.2.1
  firebase_core: ^2.4.1
  flutter_local_notifications: ^6.1.0
  firebase_analytics: ^10.1.0
  firebase_crashlytics: any

  #Remote config
  firebase_remote_config: ^3.0.9

  percent_indicator: ^4.2.2
  webview_flutter_plus: ^0.3.0+2
  autocomplete_textfield: ^2.0.1
  flutter_typeahead: ^4.0.1
  cached_network_image: ^3.0.0
  infinite_scroll_pagination: ^3.2.0
  dotted_line: ^3.1.0
  material_floating_search_bar: ^0.3.7
  audioplayers: ^2.0.0
  flutter_scatter: ^0.2.0
  connectivity: ^3.0.6
  hexcolor: ^3.0.1
  flutter_spinkit: ^5.1.0
  url_launcher: ^6.1.7
  #  keyboard_visibility: any
  lottie: ^2.2.0
  package_info_plus: ^3.0.2
  flutter_launcher_icons: ^0.11.0
  permission_handler: ^10.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/drawable-ldpi/
    - assets/images/drawable-xxhdpi/
    - assets/storypage/
    - assets/storypage/css/
    - assets/storypage/font-my/
    - assets/storypage/images/
    - assets/storypage/js/
    - assets/storypage/pages/
    - assets/storypage/tts_anim/
    - assets/audio/
    - assets/local-json/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Dosis
      fonts:
        - asset: assets/font/Dosis.ttf
        - asset: assets/font/Regular.ttf
          weight: 500
        - asset: assets/font/Dosis-Bold.ttf
          weight: 700
    - family: Poppins
      fonts:
        - asset: assets/font/Poppins-Regular.ttf
        - asset: assets/font/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/font/Poppins-Bold.ttf
          weight: 800
    - family: Montserrat
      fonts:
        - asset: assets/font/Montserrat-Regular.ttf
        - asset: assets/font/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/font/Montserrat-Bold.ttf
          weight: 800
        - asset: assets/font/Montserrat-Light.ttf
          weight: 300


